### ISSUE TITLE
name splitting

### ISSUE THREAD

**Issue by igorTT** [malinovaya0iriska/my-with-gulp-project#3]
Давай разобъём код в css немного через амперсанды
```css
.sos-footer {
  background: #080A0B;
  max-height: 233px;
  height: 100%;

  @media screen and (max-width: 350px) {
    max-height: 490px;
  }

 &__container {
    flex-direction: column;
    justify-content: space-between;
    height: 100%;
  }
}
```
